#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "


curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
    {
    	"type": "Store",
    	"id": "urn:ngsi-ld:Store:001",
    	"address": {
        	"type": "PostalAddress",
        	"value": {
            	"streetAddress": "Bornholmer Straße 65",
            	"addressRegion": "Berlin",
            	"addressLocality": "Prenzlauer Berg",
            	"postalCode": "10439"
	        }
	    },
	    "location": {
	        "type": "geo:json",
	        "value": {
	           "type": "Point",
	           "coordinates": [13.3986, 52.5547]
	        }
	    },
    	"name": {
        	"type": "Text",
        	"value": "Bösebrücke Einkauf"
    	}
    },
    {
    	"type": "Store",
        "id": "urn:ngsi-ld:Store:002",
	    "address": {
	        "type": "PostalAddress",
	        "value": {
	            "streetAddress": "Friedrichstraße 44",
	            "addressRegion": "Berlin",
	            "addressLocality": "Kreuzberg",
	            "postalCode": "10969"
	        }
	    },
	    "location": {
	        "type": "geo:json",
	        "value": {
	             "type": "Point",
	             "coordinates": [13.3903, 52.5075]
	        }
	    },
	    "name": {
	        "type": "Text",
	        "value": "Checkpoint Markt"
	    }
    }
    {
      "id":"urn:ngsi-ld:Shelf:unit001", "type":"Shelf",
      "location":{
        "type":"geo:json", "value":{ "type":"Point","coordinates":[13.3986112, 52.554699]}
      },
      "name":{
        "type":"Text", "value":"Corner Unit"
      },
      "maxCapacity":{
        "type":"Integer", "value":50
      }
    },
    {
      "id":"urn:ngsi-ld:Shelf:unit002", "type":"Shelf",
      "location":{
        "type":"geo:json","value":{"type":"Point","coordinates":[13.3987221, 52.5546640]}
      },
      "name":{
        "type":"Text", "value":"Wall Unit 1"
      },
      "maxCapacity":{
        "type":"Integer", "value":100
      }
    },
    {
      "id":"urn:ngsi-ld:Shelf:unit003", "type":"Shelf",
      "location":{
        "type":"geo:json", "value":{"type":"Point","coordinates":[13.3987221, 52.5546640]}
      },
      "name":{
        "type":"Text", "value":"Wall Unit 2"
      },
      "maxCapacity":{
        "type":"Integer", "value":100
      }
    },
    {
      "id":"urn:ngsi-ld:Shelf:unit004", "type":"Shelf",
      "location":{
        "type":"geo:json", "value":{"type":"Point","coordinates":[13.390311, 52.507522]}
      },
      "name":{
        "type":"Text", "value":"Corner Unit"
      },
      "maxCapacity":{
        "type":"Integer", "value":50
      }
    },
    {
      "id":"urn:ngsi-ld:Shelf:unit005", "type":"Shelf",
      "location":{
        "type":"geo:json","value":{"type":"Point","coordinates":[13.390309, 52.50751]}
      },
      "name":{
        "type":"Text", "value":"Long Wall Unit"
      },
      "maxCapacity":{
        "type":"Integer", "value":200
      }
    }
  ]
}'

echo -e " \033[1;32mdone\033[0m"
